### ISSUE TITLE
Order of filters in UI

### ISSUE THREAD

**Issue by bersbersbers** [vfeskov/gitpunch#126]
The filters in gitpunch.com are (from left to right):
> Major, Minor, Patch, All Releases

I think it would make sense to order them by verbosity, either 
> All, Major, Minor, Patch
or
> Patch, Minor, Major, All

**Comment by AlexWayfer** [comment]
I think you don't understand what "all" means.

Major — only when the first digit changes, the most rare notifications.
Minor — more often, patch — almost every release.
But there can be beta-versions, RC-versions, 4th-digit versions, etc., everything of that including in "All", I think, so it's the most often.
So, the order is from less often notifications to more often. Seems logical.

**Comment by bersbersbers** [comment]
Embarrassing. Yes, @AlexWayfer, of course - and sorry for the noise!
