### ISSUE TITLE
Not receiving emails anymore

### ISSUE THREAD

**Issue by Archinowsk** [vfeskov/gitpunch#175]
I haven't received emails for last five days. My last email was received 25.3. Checked junk mail and didn't find them from there either. I'm using Gmail.

![image](https://user-images.githubusercontent.com/1327412/160881001-25060748-23ca-47bd-89f5-e8d28f59d85f.png)

![image](https://user-images.githubusercontent.com/1327412/160880832-824e1fd2-421d-46a9-9c50-0feb4d784ef6.png)

**Comment by torgeirl** [comment]
Normally don't receive that many so unsure how long it's been for me - but I can point to at least one release (two days ago) that should have generated an email notification to me (yesterday), that didn't.

**Comment by yotov** [comment]
Same for me. I didn't receive any new emails after 25.03

**Comment by toha-nordic** [comment]
Experiencing the same issue here, any news regarding this?

**Comment by whoiswes** [comment]
Same here, no emails for several weeks.

**Comment by Coobaha** [comment]
As a workaround you can read RSS feeds for releases

- can recommend [NetNewsWire](https://github.com/Ranchero-Software/NetNewsWire)
  - it stores feeds on  `Subscriptions.opml` and reads them on start
  - When opened `NetNewsWire` scans `Subscriptions.opml` and imports new items and removes dupes

Here is quick and dirty script I use to import all my GitHub stars into RSS reader as a cron job, you might need to tweak it for your needs :) 

deps:
 - `zx`
 - `octokit`
 - `process.env.GITHUB_NPM_TOKEN`


```typescript
#!/usr/bin/env zx
import { Octokit } from "octokit";

const octokit = new Octokit({ auth: process.env.GITHUB_NPM_TOKEN });

const rsss = [];

const iterator = octokit.paginate.iterator(
  octokit.rest.activity.listReposStarredByAuthenticatedUser,
  {
    per_page: 100,
  }
);

const data = await fs.readFile(
  "~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts/2_iCloud/Subscriptions.opml"
);

for await (const res of iterator) {
  // comment this part if this is first run to generate all feeds
  if (data.includes(`xmlUrl="${res.data.at(0)?.html_url}/releases.atom"`)) {
    console.log("Same feed, skipping");
    break;
  }

  let templ = res.data.map((d) => {
    return `<outline text="${d.name}" title="${d.name}" description="${
      d.description ?? ""
    }" description="" type="rss" version="RSS" htmlUrl="${
      d.html_url
    }" xmlUrl="${d.html_url}/releases.atom"/>`;
  });
  rsss.push(...templ);
}

if (rsss.length) {
  await fs.writeFile(
    "~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts/2_iCloud/Subscriptions.opml",
    data
      .toString()
      .replace(
        'nnw_externalID="ICLOUD_IDXXXXXXXXXXXXX">',
        `nnw_externalID="ICLOUD_IDXXXXXXXXXXXXX">\n\t\t${rsss.join(
          "\n\t\t"
        )}`
      ),
    "utf8"
  );
  await $`osascript -e 'tell application "NetNewsWire" to quit'`;
  await $`open -g -a "NetNewsWire"`;
  await $`open -g -a "NetNewsWire"`;
}
```

**Comment by seuffert** [comment]
didn't get any new notification emails since end of march :(

**Comment by gaia** [comment]
V Feskov sounds like a Russian name. What probably happened is that he has not be able to pay or use Amazon SES to have the emails sent out.  Or maybe he was sent to that horrible war. The solution then is to fork the project and put it under another domain name.

**Comment by vfeskov** [comment]
Hey lovely people! 

I'm Ukrainian and a principal engineer at a startup and a lot has happened in my life since February, for a long time i've had a lot on my plate and deprioritized maintaining GitPunch. I keep paying for it though, no issue there. 

I suspect what happened is the change of github authentication method - i remember receiving alerts about it from github. i will look into it on the weekend but it might take more than one weekend

**Comment by gaia** [comment]
Slava Ukraini!! and thank you! (my wife is Ukranian)

**Comment by vfeskov** [comment]
Found few more bugs and fixed them, haven't seen any issues for almost a week now, so Im closing this, but please feel free to report if you spot anything. Again thanks for using GitPunch, even after 3 months of downtime, it was embarassing ngl :)

**Comment by torgeirl** [comment]
After receiving one daily email on July 11 I'm back to not receiving emails again unfortunately. As far as I can tell I should have received daily emails on at least July 13, July 17, July 22, August 3 and August 6.

> I've received some emails this week, thank you for your work.

@AlexWayfer: are you receiving daily or individual notification emails?

**Comment by AlexWayfer** [comment]
> After receiving one daily email on July 11 I'm back to not receiving emails again unfortunately. As far as I can tell I should have received daily emails on at least July 13, July 17, July 22, August 3 and August 6.
> 
> > I've received some emails this week, thank you for your work.
> 
> @AlexWayfer: are you receiving daily or individual notification emails?

Kind of groupped, but it happes a few times per day if neccessary. Example:

![image](https://user-images.githubusercontent.com/6510020/183301122-c3daf421-a6de-459f-83f2-bb652d990d56.png)

![image](https://user-images.githubusercontent.com/6510020/183301127-6482d7d6-1186-460d-8cd1-071a006275d8.png)

![image](https://user-images.githubusercontent.com/6510020/183301154-055079c5-86e0-4012-a0bb-da988aa5619d.png)

**Comment by vfeskov** [comment]
i don't see any errors/timeouts in my logs, @torgeirl can you please send me your email address to vlad@vfeskov.com, i will check your case in particular.
