### ISSUE TITLE
Github two-factor authentication login

### ISSUE THREAD

**Issue by wouterkroes** [vfeskov/gitpunch#196]
Hello,

I would like to change the notification level for all my starred repositories from the default all releases to only major releases.

I think I can do this by first getting my token via the `POST /api/sign_in` call. Then run the `PATCH /api/repos/all` call with the token for authentication. 

But the `POST /api/sign_in` call fails, I think this is because I have github two-factor authentication turned on? How do I authenticate to gitpunch with two-factor authentication turned on?

Many thanks for this great project!

Greetings,

Wouter

**Comment by vfeskov** [comment]
Hi Wouter, i didn't even think of this scenario, the easiest and the quickest way for me would be to set a password hash for your account, would that work for you?

If yes then please generate a hash [here](https://codesandbox.io/s/node-playground-forked-rmhogn?file=/index.js):

<img width="1440" alt="Screenshot 2022-10-24 at 23 22 46" src="https://user-images.githubusercontent.com/2743367/197632204-8652e0e6-f676-4d85-a6cc-140dfd713033.png">

1. Change the value of the `password` variable in the middle section to your new password
2. Open Console section in the bottom right corner
3. Copy and send me the password hash from Console to vlad@vfeskov.com

Then I'll write you back and you'll be able to sign in using the password from step 1.
