### ISSUE TITLE
Skip PATCH releases

### ISSUE THREAD

**Issue by bozheville** [vfeskov/gitpunch#20]
Could you please add an ability to skip `patch` releases so I can track only `major` and `minor`?

**Comment by TPS** [comment]
_Does_ GitHub actually have a _standard_ method to differentiate these release types?

**Comment by bozheville** [comment]
@TPS no, it doesn't unfortunately. You can put "Lorem ipsum dolor sit amet" to your version field.

@vfeskov sometimes minor releases can contain also patch version mark, like `0.1.2-rc.3` can be the first release with that `1` in the middle.

**Comment by vfeskov** [comment]
@bozheville i mean for example `v5.4.0` is a minor release, and `v5.0.0` is a major, `v5.0.1` or `v5.0.0-rc.3` are both patch releases.

like if it ends with exactly `.0` then it's a minor release, and if it ends with exactly `.0.0` then it's a major one.

but then again it's gonna be user's responsibility to make sure the repo does follow semantic versioning

**Comment by torgeirl** [comment]
> i'm thinking of adding a setting to send email when release number contains zero in the right place (...) this way could also filter out releases like `v6.0.0-rc.6`

@vfeskov: this sounds like a good feature. Just to come with an example my needs for notifications are very repository dependent:

- some I depend on as a developer, and just need to know of the major releases (breaks)
- certain web applications I manage instances of at work, and need to know every patch (security)
- others I work on or follow, and would like to know every release of (including RCs)

It would be great if I could toggle between

- every release
- patches (but no dashes, like RCs)
- minors
- majors

As I understand it that's what you suggest in your last post + differentiating between (security) patch and release candidate.

**Comment by PaulAnnekov** [comment]
@vfeskov https://github.com/home-assistant/home-assistant/releases. I want to get only non-beta releases. Beta is when it has "pre-release" mark, also ends with `b[0-9]`. Looks like your algorithm won't help me, because `0.77.0b0` will be patch release, `0.77.0` will be minor release and `0.77.1` will be patch release and I want to get `0.77.0` and `0.77.1`, but not `0.77.0b0`.

**Comment by vfeskov** [comment]
@PaulAnnekov :+1:

**Comment by PaulAnnekov** [comment]
If you still want to deal with all this version mess among different repositories, you can implement "pre-release" marks as one more option:
- every release
- pre-release ("pre-release" mark)
- patches (but no dashes, like RCs)
- minors
- majors

**Comment by vfeskov** [comment]
@PaulAnnekov looks like pre-release mark is not available in atom feeds: https://github.com/home-assistant/home-assistant/releases.atom , only via API, which has rate limits. Because of those I had to switch to atom feeds and I don't think supporting pre-release option is worth going back to API

**Comment by PaulAnnekov** [comment]
Is it a problem to use API when user selected "pre-release" and atom for other options? Also can you explain what rate limits did you encounter?

**Comment by vfeskov** [comment]
done, will describe in release notes

**Comment by TPS** [comment]
@vfeskov This makes a potential new sort option — by notification level: muted, major, minor, patch/all, which helps 1 quickly determine what 1 did (but perhaps didn't mean to 😳)
