### ISSUE TITLE
Problems getting updates from GitHub, temporary no realtime -> every 10 minutes instead

### ISSUE THREAD

**Issue by vfeskov** [vfeskov/gitpunch#25]
Current polling model doesn't work well anymore, GitHub atom feeds cannot sustain this many requests, even if i send them in [groups of 50 every 125ms](https://github.com/vfeskov/gitpunch/blob/fea34f7a9160d862f47ebf2d3b595d727099b900/notifier/src/parts/fetchTags.ts#L14) and [retry failures 5 times with 1 second delay](https://github.com/vfeskov/gitpunch/blob/fea34f7a9160d862f47ebf2d3b595d727099b900/lib/src/githubAtom.ts#L25). 

Plus the polling script takes much more memory, time and uploads too much megabytes, which increases costs.

@soulim told me about [PubSubHubbub](https://developer.github.com/v3/repos/hooks/#pubsubhubbub), which wasn't easy for me to find in GitHub docs when I started this project. Seems like this is the perfect solution, but it requires rewriting like half of what's already there.

Some release emails may be delayed until the PubSubHubbub refactoring is complete

UPDATE: increasing interval between batch requests and delay between attempts (https://github.com/vfeskov/gitpunch/commit/609d4234b8098ff02f8c73c3fe2e757bf6c8c438) worked quite well, but because of number of monitored repos exploding I have to **temporary disable realtime and check for updates every 20 minutes**.

UPDATE: i can afford checking **every 10 minutes** until i finish refactoring

**Comment by soulim** [comment]
Feel free to ask any questions. I'm happy to help 😄

**Comment by vfeskov** [comment]
@soulim man it seems like github only allows subscribing if you own the repo 😭 

I created `hugebullet/test-events` and `facebook/react` repos, and tried to subscribe from my main account:
```
local:~ user$ curl -u "vfeskov" -i \
>   https://api.github.com/hub \
>   -F "hub.mode=subscribe" \
>   -F "hub.topic=https://github.com/hugebullet/test-events/events/release.json" \
>   -F "hub.callback=https://xxx.execute-api.us-west-1.amazonaws.com/prod"
Enter host password for user 'vfeskov':
HTTP/1.1 100 Continue

HTTP/1.1 422 Unprocessable Entity
Server: GitHub.com
Date: Sat, 05 May 2018 10:51:57 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 204
Status: 422 Unprocessable Entity
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4990
X-RateLimit-Reset: 1525519886
X-GitHub-Media-Type: github.v3; format=json
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-Runtime-rack: 0.052260
X-GitHub-Request-Id: E3FD:5842:2BDF071:59CA75D:5AED8CCD

{
  "message": "No repository found for hub.topic: \"https://github.com/hugebullet/test-events/events/release.json\"",
  "documentation_url": "https://developer.github.com/v3/repos/hooks/#pubsubhubbub"
}
```
(same response for react)

Then I created `vfeskov/test-events`, which my main account owns, and subscribed successfully:
```
local:~ user$ curl -u "vfeskov" -i \
>   https://api.github.com/hub \
>   -F "hub.mode=subscribe" \
>   -F "hub.topic=https://github.com/vfeskov/test-events/events/release.json" \
>   -F "hub.callback=https://xxx.execute-api.us-west-1.amazonaws.com/prod"
Enter host password for user 'vfeskov':
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Server: GitHub.com
Date: Sat, 05 May 2018 10:54:49 GMT
Content-Type: application/octet-stream
Status: 204 No Content
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4989
X-RateLimit-Reset: 1525519886
X-GitHub-Media-Type: github.v3; format=json
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-Runtime-rack: 0.081234
X-GitHub-Request-Id: E3FE:5842:2BE4152:59D4C67:5AED8D78
```

I also was able to subscribe to `hugebullet/test-events` using `hugebullet` account.

Do you know if there's a way to subscribe to repos without owning them?

**Comment by soulim** [comment]
@vfeskov that is weird. Usually public repos are open this kind of things. I'll need to play with the subscription functionality to give you more detailed answer.

Btw, `HTTP/1.1 422 Unprocessable Entity` response looks a bit suspicious. Usually 422 means something wrong with your request, e.g. bad formatting or missing required fields.

**Comment by vfeskov** [comment]
@soulim I sent the same request to the repo I own and it succeeded with 204 No Content, which makes me think the format is fine 

422 could just mean a generic request error, meaning the user should not try to repeat it, and it makes sense if my suspicion is correct - you can't request to subscribe to repo which you don't own

**Comment by vfeskov** [comment]
i have this crazy backup idea of programmatically clicking Watch button on all the repos and parsing emails from github, what do you think?

**Comment by soulim** [comment]
Played with options today. You are right, it possible to subscribe to your own repos only 🙄

It's possible to watch public events for repos, but that gives tons of "garbage" events and it isn't possible to filter them by the type. However Events API is designed for polling, so seems like that is the supposed way to go.

**Comment by vfeskov** [comment]
@soulim so even events api requires polling those events?

**Comment by soulim** [comment]
I don't know why, but `ETag` header is not available for Atom feeds.

**Comment by soulim** [comment]
@vfeskov yep, you have to poll the Events API. You are allowed to make 60 requests per minute. The API returns all possible events which could be a lot of bytes to transfer 😄

**Comment by vfeskov** [comment]
@soulim looks like it also supports pagination to fetch up to 300 most recent events, they also send `X-Poll-Interval` header that tells how often to poll, right now it says 1 minute. Tried with OAuth token and it didn't have any effect.

I sure hope it is always possible to read all events that happened in the last minute, because 300 seem like not so many. Like, if 500 events happened in last minute, you could only get last 300 of those 😨 

Probably they do let you get all of the events all the time, and using it is going to be much better than polling atom feeds, since it's 10 api requests (30 events x 10 pages) vs 11 000 atom requests. Polling API would cost me nothing, but respecting `X-Poll-Interval` header is going to be a challenge with AWS Lambda running in regular intervals, I guess I'll have to poll on server.

thanks man for all the help and research 👍

**Comment by vfeskov** [comment]
i wrote a little script tracking how latest event id increments between requests, turns out there are 1600 events happening every minute on average

**Comment by vfeskov** [comment]
i gave it another thought

**Comment by vfeskov** [comment]
Right now it's 5400 events per minute, or 90 per second. Probably it's even more at peak times, so I better request all 10 pages of events (300 events) every second, which is 36k requests per hour -> 8 github accounts to stay below rate limit

These 36k are more than I do now polling atom feeds, but it's a fixed number and it will not increase with more users. Having atom feeds as a backup strategy I can poll them much less frequently too -> less requests overall

**Comment by soulim** [comment]
Well, sounds like a good solution 😄

**Comment by vfeskov** [comment]
@gomaak suggested further optimisation: it's possible to detect if some events were missed simply by checking event IDs, and fetching atom feeds can be triggered when there were some events missed. Effectively it would mean that fetching atom would almost never happened, which is great

**Comment by vfeskov** [comment]
ok so i can't detect if some public events were missed between poll requests and between pages because it's now obvious that some events are private and all events share same id sequence

**Comment by vfeskov** [comment]
all done and deployed! 🎉 

server fetches last 150 gitpub public events every second, puts release events into SQS queue where they stay invisible for 30 seconds, then notifier script picks up the events and sends emails only about those. every hour the notifier script will ignore events and fetch releases of all repos -> a backup strategy if some release events were missed

documented it in readmes too: https://github.com/vfeskov/gitpunch#overview-of-code

let me know if you have any more ideas
