### ISSUE TITLE
Gitpunch website problem

### ISSUE THREAD

**Issue by beeing** [vfeskov/gitpunch#27]
Hi, after sign in via GitHub, the page will be downloaded as a html file instead of showing on browser.

**Comment by aliusmiles** [comment]
+1, works OK in Chrome, but downloads page in Safari.

**Comment by vfeskov** [comment]
@beeing @aliusmiles what browser and version does that? Works fine for me in Safari 11.0.3, Chrome and FF. Also which domain are you using, gitpunch.com?

**Comment by beeing** [comment]
@vfeskov I'm on Safari Version 11.1 (13605.1.33.1.4) accessing gitpunch.com

Chrome is working fine though. Btw, any idea why some starred repo watch cannot be enabled?

**Comment by aliusmiles** [comment]
@vfeskov, Safari Version 11.1 (13605.1.33.1.4), gitpunch.com

**Comment by aliusmiles** [comment]
Btw, the same issue with Safari on iOS.

MacOS User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15`

iOS User Agent: `Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1`

Although issue doesn't seem to be in UserAgent - I've tried to change it in Safari's Develop menu, still downloading page.

**Comment by vfeskov** [comment]
thanks for additional info peeps, i will try to reproduce and fix it ASAP

**Comment by vfeskov** [comment]
there was an embarrassing typo in content-type of the server response, it's fixed now, tell me if the bug still happens i'll reopen
