### ISSUE TITLE
Cleanup email subject and body

### ISSUE THREAD

**Issue by ThomasKientz** [vfeskov/gitpunch#28]
Hi,

Actually a subject looks like 
>New GitHub Release: angular/universal - v6.0.0

I suggest to delete "New GitHub Release: " and so to reduce entropy of emails and improve readability. Since the email is coming from "releases@beer.vfeskov.com" we already know that it is about a github release, so its redundant.

You could also remove this from the email body :

> Greetings :)
> Happy to tell you that a new release has happened:

Gitpunch is a great alternative to Sibbel. Thank you for the very good work. Love the ability to subscribe to all my stared projects 👍

**Comment by vfeskov** [comment]
@TPS  yeah replacing sender has been due for a long time, why I haven't done it yet is because of having to go through verification process with AWS again and the fact that it'll break email filters.

anyway im going to do it sooner or later

**Comment by TPS** [comment]
@vfeskov This needs a little more tweaking. Here's my __subject__ line from last e-mail:
<Details>
zfsonlinux/zfs@zfs-0.7.9, blokadaorg/blokada@3.4.100500, EFForg/privacybadger@release-2018.5.10, vim/vim@8.0.1813, vim/vim@8.0.1812, vim/vim@8.0.1811, vim/vim@8.0.1810, vim/vim@8.0.1809, vim/vim@8.0.1808, vim/vim@8.0.1807, transloadit/uppy@0.24.3, opengapps/arm@20180510, jedisct1/dnscrypt-proxy@2.0.12, JetBrains/kotlin@build-1.2.50-dev-1250, JetBrains/kotlin@build-1.2.50-dev-1245, JetBrains/kotlin@build-1.2.50-dev-1243, JetBrains/kotlin@build-1.2.50-dev-1240, JetBrains/kotlin@build-1.2.50-dev-1237, JetBrains/kotlin@build-1.2.50-dev-1236, JetBrains/kotlin@build-1.2.41-release-75, renyuneyun/Easer@0.5.9, gitlabhq/gitlabhq@10.8.0-rc7, brave/browser-laptop@0.23.4developer, brave/browser-laptop@0.23.3developer, Mottie/GitHub-userscripts@1.0.179, gorhill/uBlock@1.16.5rc0, pbatard/rufus@b1274, pbatard/rufus@b1273, pbatard/rufus@b1272, WireGuard/wireguard-android@0.4.5, Aris-t2/CustomCSSforFx@1.8.5, syncthing/syncthing@0.14.48-rc.3, FortAwesome/Font-Awesome@5.0.13, opengapps/arm64@20180510,
</Details><br>
So, this has a few issues re: redundancy/duplication b/c it shows multiple releases from same repo non-intuitively.  Better if version #s were either:<br>
  • Skipped outright, & then multiple mentions compressed to just 1: repo/repo, repo1/repo1<br>
  • Listed _after_ a single mention of repo: repo/repo@0.1,0.2,0.3, repo1/repo1@0.4,0.5,0.6<br>
That'd fix the massive redundancy, lack of reading clarity, & allow more repos to fit in the subject.

**Comment by vfeskov** [comment]
@TPS my idea was that having full repo@version format would be easier to setup email filter for, e.g. you can catch `angular/angular@7.0.0` release by simply filtering the subject by it. 

@ThomasKientz what do you think?

**Comment by vfeskov** [comment]
good point, i didn't consider filtering by body, but i still would like to see versions in the subject. i guess i'll do `angular/angular@6.9.1,7.0.0`

**Comment by TPS** [comment]
Maybe (possibly configurable) different behavior when doing individual e-mail vs digest?

**Comment by vfeskov** [comment]
guys i shortened subject here 495eaf5 , examples:
- when there are multiple repos: `material-ui@1.0.0; react@16.3.2`

- when there are multple releases of a repo: `angular@5.2.11, 6.0.2; vue@2.5.16, 2.5.15`

tell me what you think

**Comment by TPS** [comment]
It's just what I wanted, so it's great. (Sorry about delay: I'd to wait for my daily, scheduled e-mail.) :bow:

**Comment by ThomasKientz** [comment]
@vfeskov Hi !

IMO, the `from` object should be "GitPunch", instead of "releases@beer.vfeskov.com".  That will be cherry on top, everything else is perfect !

**Comment by TPS** [comment]
@vfeskov A _very_ minor RFE to this & #38:

Could these be sorted in ascending (oldest to newest) order _within_ each of these repos (perhaps optionally)?  Certain repos (e.g., [vim](https://github.com/vim/vim/releases) & [chromium](https://github.com/chromium/chromium/releases/)  will have ½ a dozen releases a day, & the changelogs don't make much sense in the current, reversed order.

**Comment by vfeskov** [comment]
Totally. Should I keep the reversed order in title? @TPS

**Comment by TPS** [comment]
No, keep it consistent & obvious, as things are much easier to follow in ascending order, everyplace, AFAIK.

**Comment by TPS** [comment]
@vfeskov Thanks very much for https://github.com/vfeskov/gitpunch/commit/d08b5822ff3ac93f457543267c3040c6cc5b7bf4 : it's perfect.
