### ISSUE TITLE
Unable to enable specify repos watching

### ISSUE THREAD

**Issue by AlexWayfer** [vfeskov/gitpunch#29]
Hello! I can't enable watching for following repos:
* `sallar/github-contributions-chart`
* `philipwalton/flexbugs`
* `rubygarage/api_struct`
* `opal/opal-browser`

Console:

```
api.js:14 POST https://gitpunch.com/api/repos 400 ()
````

Thank you.

**Comment by vfeskov** [comment]
@AlexWayfer these repos do not have any releases on GitHub, so they probably never will and monitoring them would be a waste of resources, that's why gitpunch.com doesn't allow such repos to be watched

**Comment by AlexWayfer** [comment]
> @AlexWayfer these repos do not have any releases on GitHub, so they probably never will and monitoring them would be a waste of resources, that's why gitpunch.com doesn't allow such repos to be watched

Thank you for clarification.

I'm ready to donate/pay for GitPunch, or try to deploy somewhere myself (so, it can have an option, disabled by default, which I'll able to enable), but I want to be notified if any of these repos will use tags/releases.

**Comment by vfeskov** [comment]
I'll include removal of this limitation with #25 resolution. 

By minimal deployment I meant not deploying Web interface at all and just modifying db directly. For Web interface you'd have to configure more things, I think server's README.md should have all the required info
