### ISSUE TITLE
Lost my subscription during migration from winabeer to gitpunch

### ISSUE THREAD

**Issue by tsupertramp** [vfeskov/gitpunch#30]
Hey Ho,

first of all - awesome project. Really love it :) Makes my life easier.

If you every are in Germany in cologne / duesseldorf give me shoutout would love to meet you in person!

Now the sad subject: During migration from winabeer to gitpunch i lost all my subscriptions. Account was connected through github.

Greetings, Thomas

**Comment by vfeskov** [comment]
thanks man, would be cool to meet

i looked up your github username in the db and i see that there are two matching email address, one with `+github` suffix, and one without.

the way it works now when you sign in with github it either logs you in or registers new account, it depends on whether your github email was registered already or not

i think what happened was you signed up having one email on github, changed it on github and signed up with the new email. did i guess right? if you want i can transfer your watched repos from old account to new one, or you can switch back to your old email on github and use the old account

**Comment by tsupertramp** [comment]
Ah yeah you are right, i changed my main github email. That explains it. Will fix it myself. Just was afraid that it was due to migration and could happen to other ones as well. - Thanks for your work!
