### ISSUE TITLE
Improve styling of emails so they look more modern

### ISSUE THREAD

**Issue by Jacalz** [vfeskov/gitpunch#34]
Right now the emails look very basic and only have text, would look way better if they had some css styling or something like Sibbell:

Current look:
![image](https://user-images.githubusercontent.com/25466657/40495379-5fbbc72a-5f77-11e8-9665-310d0202b90d.png)

Look of dead Sibbell emails:
![image](https://user-images.githubusercontent.com/25466657/40495438-7d7fbfbe-5f77-11e8-9e92-1ceefda22789.png)

Example list of thing that can be done to improve styling:

- Add hyperlinks
- Add logo of the GitHub project if it has one
- Some styling with elements using CSS
- Different size of text to make it pop more

**Comment by svenluijten** [comment]
To be honest I prefer the "simple" emails. Just like the ones you'd get from GitHub normally, this makes it already easy to scan and readable on every device.

**Comment by Jacalz** [comment]
It is the absolute opposite for me because I find it harder to read those simple emails because all looks the same to me 😅

**Comment by Jacalz** [comment]
Thanks for fixing this @vfeskov 👍
