### ISSUE TITLE
Emails preview

### ISSUE THREAD

**Issue by AlexWayfer** [vfeskov/gitpunch#43]
Hello!

I want to make some style improvements for email.

How can I look at emails preview (with repo launched on my side)?

**Comment by vfeskov** [comment]
what do you mean? are you talking about some email client's feature?

**Comment by AlexWayfer** [comment]
For example, I want to try to increase `font-size`. Or add `background-color` for `<code>`.

**Comment by vfeskov** [comment]
ah, https://github.com/vfeskov/gitpunch/blob/master/notifier/src/parts/email.ts#L66-L89

**Comment by AlexWayfer** [comment]
@vfeskov Thank you, I found this code. But I'm asking for ability to **preview** changes in this code, without email sending (some release waiting). Like "email development mode", "email live preview".

**Comment by vfeskov** [comment]
hmm https://testi.at ? i was just sending emails to myself when developing ¯\_(ツ)_/¯

**Comment by AlexWayfer** [comment]
@vfeskov OK, how did you send them to yourself? How did you trigger this code above?

**Comment by vfeskov** [comment]
I ran the notifier script on local db, where my user was alerted of a previous version of a repo, but not the latest one. I also disabled updating db

To setup notifier script check readme
