### ISSUE TITLE
Shortcuts to github project

### ISSUE THREAD

**Issue by ThomasKientz** [vfeskov/gitpunch#46]
Would be awesome to have a button that opens the project's GH repo in a new page.

<img width="663" alt="capture d ecran 2018-08-19 a 16 41 47" src="https://user-images.githubusercontent.com/10157845/44309983-3f475f80-a3cf-11e8-87b0-6650c969389c.png">

**Comment by vfeskov** [comment]
closed in https://github.com/vfeskov/gitpunch/commit/b933e5f484ccaaa3238eb8167bee938ee9e4a94a
