### ISSUE TITLE
Add config to ignore "pre-release" releases

### ISSUE THREAD

**Issue by PaulAnnekov** [vfeskov/gitpunch#47]
It will be good to have a global and per-repo config to ignore "pre-release" releases. Sometimes you don't care about them and want them to don't make a mess in your inbox.
As an alternative, we can think about adding some marker in an email (in a title?), to be able to add an easy filter for repo name AND "pre-release" marker.

**Comment by PaulAnnekov** [comment]
This one is easier to implement. There is "pre-release" tag already exists so it's easy to filter releases. #20 requires some magic to get "patch" version part from `[0-9a-z]+` version.

**Comment by vfeskov** [comment]
@PaulAnnekov i think https://github.com/vfeskov/gitpunch/issues/20#issuecomment-393442713 covers your requirement, I will also add the option to change this config globally for all repos

closing this one in favor of #20
