### ISSUE TITLE
BUG: Bell stays blue after clicking

### ISSUE THREAD

**Issue by aeimer** [vfeskov/gitpunch#48]
I don't know if it's a wanted behaviour, but if you hover a repo the bell is grey. After clicking it it turns blue, but does not goes back to grey after clicking it again...

**Comment by vfeskov** [comment]
@aeimer can you tell on which OS and browser it happens?

**Comment by aeimer** [comment]
@vfeskov I tried it on Windows 10 and (the latest) Firefox

**Comment by aeimer** [comment]
BTW, the error still exists. I hoped it would be fixed with the latest releases... :/

**Comment by aeimer** [comment]
Seems to be ok
