### ISSUE TITLE
Email should have a link to the repo itself

### ISSUE THREAD

**Issue by Vad1mo** [vfeskov/gitpunch#50]
The Current notification Email only a links to the release. 
I propose to change the links and add an additional link.

**Current**
<img width="739" alt="bildschirmfoto 2018-08-31 um 08 25 27" src="https://user-images.githubusercontent.com/1492007/44896074-3facf800-acf7-11e8-918b-d331d2317927.png">

**Change**
The GitHub Link that currently points to the release should point to the repository.
The Version Number in the Title should point to the release.

<img width="739" alt="bildschirmfoto 2018-08-31 um 08 25 27" src="https://user-images.githubusercontent.com/1492007/44896351-3ff9c300-acf8-11e8-8f3d-9fb47623e6b8.png">

For maybe a better user experience to put both into the title.
**Change (Option 2)**
<img width="739" alt="bildschirmfoto 2018-08-31 um 08 25 27" src="https://user-images.githubusercontent.com/1492007/44900261-70dff500-ad04-11e8-8374-31ad289c12d3.png">

Let me explain why that makes sense to change the links.

Usually the users are interested in what did actually change in the release, this information is provided in the email itself already. Usually it is not the case that you still go to the release page, unless you want to download the binaries.  More then often you are following more then a few repositories and in my case I don't always know what the repository is good for based on the release note. So I go to the repo and lookup the basic information.

I think it is a good practice if we would provide a link to the repo itself.

**Comment by aliusmiles** [comment]
Would be even nicer to have direct link to CHANGELOG file, but since it could be named/located differently I guess that's could cause issues..

**Comment by Vad1mo** [comment]
🎉 

thank you
