### ISSUE TITLE
RFC/E: AstralApp instance integration

### ISSUE THREAD

**Issue by TPS** [vfeskov/gitpunch#51]
@vfeskov In short, it's a nifty way to organize 1's ★ed repos, & would solve #37.

Details/screenshots @ https://astralapp.com/, source @ https://github.com/astralapp/astral.

To actually run on G👊's public service, you might have to get special permission from @Syropian due to [BSD-3-Clause licensing](https://github.com/astralapp/astral/blob/master/LICENSE).…

**Comment by vfeskov** [comment]
how do you envision it? info from astralapp shown next to each repo on gitpunch?

**Comment by TPS** [comment]
@vfeskov The way I figure, AstralApp could be presented as the (optional? advanced?) website front-end/UI to manage the repo-list (below "E-mails are on" options), to complement all the extraordinary backend work you've done, as well as your bread-&-butter e-mail notifications. But…

@Syropian, what do you think of https://gitpunch.com/ ?  Do you think your AstralApp mashed-up w/ it could be licensed w/o fuss/cost?

**Comment by syropian** [comment]
I'm not sure I want to reduce Astral to a piece of UI that gets assimilated into another differently-branded project. If anything, it would almost make _more_ sense to do it the other way around and integrate GitPunch into Astral, since Astral has a more complex UI already in place. However I'll totally leave that up to @vfeskov, I have no intention of integrating GitPunch functionality into Astral otherwise, and respect all the work he's put in to it.

**Comment by TPS** [comment]
@syropian That's fine, except you've no public instances yourself – each user is expected to run their own instance someplace.  Since @vfeskov runs a public UI to manage ★ed Repo Notifications, I'm hoping Astral could be a kind of upgrade to that UI, but including all that G👊 goodness on top.

**Comment by syropian** [comment]
@TPS No public instances? What about https://astralapp.com ? 😅

**Comment by TPS** [comment]
_OT: @syropian Does it show up on mobile? How would 1 login?  All I see is the info _about_ it, along w/ lotsa screenshots of it hosted on https://astral.test .…_

**Comment by syropian** [comment]
@TPS You can't sign in on mobile because the app is not optimized for mobile.

**Comment by TPS** [comment]
@syropian So, basically invisible to most of us, anyway, even if there were to be G👊 ↔️ Astral integration in some form.  I've opened https://github.com/astralapp/astral/issues/220, & will close this pending that.
