### ISSUE TITLE
Import / Export user configuration

### ISSUE THREAD

**Issue by HorlogeSkynet** [vfeskov/gitpunch#62]
Hello Vlad,

I was just wondering today if it could be possible for us to (import /) export our GitPunch configuration.
It could mitigate any migration issue (as when you drafted the v1.10.0 :wink:), and / or encourage quick and easy transfers towards personal instances (#decentralization).

Anyway, a big thank to you for this awesome solution, the daily email is very appreciated :ok_hand:

Bye :wave:

> PS : Should not the intro be tweaked a bit as [GitHub allows us now to watch for new releases](https://blog.github.com/changelog/2018-11-27-watch-releases/) ? :stuck_out_tongue_winking_eye:

**Comment by vfeskov** [comment]
Hey hey, how do you mean import/export would solve v1.10.0 issue? People having their own backups?

Regarding export, does this work for you https://gitpunch.com/api/profile ? or you need raw database entry in `users` collection?

would import function be useful to you personally? any idea how it should look like, a csv?

**Comment by HorlogeSkynet** [comment]
Hey back Vlad (happy new year ! 🎉), well I didn't know about the available API, and it looks like it already provide all the needed information for an import / export feature (apart from the user ID that would need to be ignored of course).

About your question : Yes, users would keep their profile backup somewhere somehow.

In the long run, yes it would maybe for me, but surely for others in the future if the feature is available 😏

👋

**Comment by HorlogeSkynet** [comment]
So I guess the following would work (for anyone interested) on a fresh instance with an existing profile :

```bash
curl \
	-X GET
	-b 'token=xxxxxxxxxxxxxxxxxxxxxx' \
	https://gitpunch.com/api/profile > profile.json

curl \
	-X PATCH \
	--data @profile.json \
	-b 'token=xxxxxxxxxxxxxxxxxxxxxx' \
	-H 'Content-Type: application/json' \
	https://your.gitpunch.instance/api/profile
```

Closing here, thanks.
