### ISSUE TITLE
No description in E-Mail

### ISSUE THREAD

**Issue by Vad1mo** [vfeskov/gitpunch#96]
The last two days, I received emails without any descriptions. Everything was  "No description". 
I few days before that I got one email without any description but then it was ok until now.

![image](https://user-images.githubusercontent.com/1492007/80192154-100eda00-8617-11ea-8959-7b94eac076f4.png)

**Comment by vfeskov** [comment]
even though i request one link at a time from github, i still get rejected after certain number of requests. In https://github.com/vfeskov/gitpunch/commit/68491bae799b50e3b5693259cf0f5dc6f0ca019e i added a delay before retrying a  request when i start getting rejected - hopefully it'll fix the issue

**Comment by vfeskov** [comment]
issue looks to be fixed, i'll keep monitoring though. thanks for reporting!
