### ISSUE TITLE
sometimes gitpunch adds "READ MORE" links even if it isn't needed.

### ISSUE THREAD

**Issue by Vad1mo** [vfeskov/gitpunch#98]
Related to #97 

Some notification boxes  contain READ MORE links but if you follow the link, the actual content on github is exactly the same as in the email. Nothing is abbreviated.  

in some cases gitpunch attaches "READ MORE" links even if it isn't needed.

Here are two examples, where content is exactly the same in the mail and on github.
![image](https://user-images.githubusercontent.com/1492007/82643337-a121a280-9c0f-11ea-98fa-25f740b50792.png)

Here the link abbreviation with READ MORE works as expected.
![image](https://user-images.githubusercontent.com/1492007/82643195-6881c900-9c0f-11ea-92f1-caa4537926e4.png)

**Comment by vfeskov** [comment]
thanks for reporting
